#ifndef WYN_COMMON_H
#define WYN_COMMON_H

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef enum {
    TOKEN_EOF,
    TOKEN_INT, TOKEN_FLOAT, TOKEN_STRING, TOKEN_IDENT,
    TOKEN_FN, TOKEN_STRUCT, TOKEN_ENUM, TOKEN_TYPE, TOKEN_IMPL,
    TOKEN_VAR, TOKEN_CONST, TOKEN_MUT, TOKEN_PUB,
    TOKEN_IF, TOKEN_ELSE, TOKEN_MATCH, TOKEN_FOR, TOKEN_WHILE, TOKEN_IN,
    TOKEN_BREAK, TOKEN_CONTINUE, TOKEN_RETURN,
    TOKEN_IMPORT, TOKEN_FROM, TOKEN_AS,
    TOKEN_TRUE, TOKEN_FALSE,
    TOKEN_TEST, TOKEN_ASSERT,
    TOKEN_SOME, TOKEN_NONE, TOKEN_OK, TOKEN_ERR,
    TOKEN_SPAWN, TOKEN_CHANNEL,
    TOKEN_AND, TOKEN_OR, TOKEN_NOT,
    TOKEN_PLUS, TOKEN_MINUS, TOKEN_STAR, TOKEN_SLASH, TOKEN_PERCENT,
    TOKEN_AMP, TOKEN_PIPE, TOKEN_CARET, TOKEN_TILDE, TOKEN_LSHIFT, TOKEN_RSHIFT,
    TOKEN_EQ, TOKEN_EQEQ, TOKEN_BANG, TOKEN_BANGEQ,
    TOKEN_PLUSEQ, TOKEN_MINUSEQ, TOKEN_STAREQ, TOKEN_SLASHEQ,
    TOKEN_LT, TOKEN_GT, TOKEN_LTEQ, TOKEN_GTEQ,
    TOKEN_LPAREN, TOKEN_RPAREN, TOKEN_LBRACE, TOKEN_RBRACE, TOKEN_LBRACKET, TOKEN_RBRACKET,
    TOKEN_COMMA, TOKEN_COLON, TOKEN_SEMI, TOKEN_DOT, TOKEN_DOTDOT, TOKEN_ARROW, TOKEN_FATARROW, TOKEN_QUESTION,
} TokenType;

typedef struct {
    TokenType type;
    const char* start;
    int length;
    int line;
} Token;

#endif
